services:
  - type: web
    name: enlite-backend
    env: docker
    repo: https://github.com/srinivas-191/enlite
    region: singapore
    plan: free
    branch: main
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: "backend.settings"
